"""empty message

Revision ID: 18ade7f0ff0b
Revises: 
Create Date: 2023-11-13 01:30:37.386601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ade7f0ff0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_sorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sortName', sa.String(length=30), nullable=True),
    sa.Column('sortDescription', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_sorts_id'), 'blog_sorts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('blog_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labelName', sa.String(length=30), nullable=True),
    sa.Column('labelDescription', sa.String(length=100), nullable=True),
    sa.Column('sortId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sortId'], ['blog_sorts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_labels_id'), 'blog_labels', ['id'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articleTitle', sa.String(length=100), nullable=True),
    sa.Column('articleCover', sa.Text(), nullable=True),
    sa.Column('articleContent', sa.Text(), nullable=True),
    sa.Column('viewCount', sa.Integer(), nullable=True),
    sa.Column('likeCount', sa.Integer(), nullable=True),
    sa.Column('commentStatus', sa.Boolean(), nullable=True),
    sa.Column('commentCount', sa.Integer(), nullable=True),
    sa.Column('recommendStatus', sa.Boolean(), nullable=True),
    sa.Column('createTime', sa.Integer(), nullable=True),
    sa.Column('updateTime', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('sortId', sa.Integer(), nullable=True),
    sa.Column('labelId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labelId'], ['blog_labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sortId'], ['blog_sorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_blog_labels_id'), table_name='blog_labels')
    op.drop_table('blog_labels')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_blog_sorts_id'), table_name='blog_sorts')
    op.drop_table('blog_sorts')
    # ### end Alembic commands ###
